# -*- coding: utf-8 -*-
"""State_Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15FbGk-xyWshjdXpg7VOt2ZO9pZj40Fvt
"""

#pip install pandas
import pandas as wachira
#Creating dateframe from CSV
df = wachira.read_csv('/content/states.csv')
#Display dataframe
#df

#Display all state columns
wachira.set_option('display.max_columns', 51)

#Display all  rows
df.head()

#Shows no. of rows and columns
df.shape

#Display columns
df.columns

#Displays statistical analysis of viable data
df.describe()

df.columns.tolist()

#Transposes the display - rows become columns
df.describe().T

#Counts the no. of values in the series - int
df['actuals.cases'].value_counts()

#Access particular columns(series)
df['state']

#Access rows of dataframe
df.iloc[18]

#Access multiple rows
df.loc[[4,6,9,10,35],['state','actuals.hospitalBeds.capacity','actuals.deaths']]

df.loc[7:20, 'actuals.cases': 'actuals.newCases']

df = wachira.read_csv('/content/states.csv')
#Make 'state' the index
df.set_index('state', inplace= True)
#display
df.head()

#Check index
df.index

df.loc['PA']

#Setting the index when loading CSV File
df = wachira.read_csv('/content/states.csv', index_col='fips')
df

#Making column names upper case
#Updating the data frame
df.columns = [x.upper() for x in df.columns]
df.tail()

#rename columns
df.rename(columns={'fips': 'id'}, inplace=True)
df.head()